### ISSUE TITLE
d64.encodeHigh (leaving overhanging bits as 1)

### ISSUE THREAD

**Issue by jonasfj** [dominictarr/d64#2]
My suggestion is to add an `d64.encodeHigh` method, which does the same as `d64.encode` except the overhanging bits are left as `1` instead of zero.

I certainly don't want to store strings with overhanging bits as high. But it's useful when doing prefix matching of d64 encoded strings using comparison operators. See my use-case below and tell me if I'm crazy :)

---

My use-case is composite string keys in azure table storage, where you have `<`, `<=`, `>=,`>´ and `=` operations for comparison. For simplicity let's just consider any key value store with URL-safe string keys and comparison operations `<`, `<=`, `>=,`>´ and `=`.

I've figured that if I encoded the entries `k1` and `k2` in my composite key with d64 and use `!` as separator, the order will be preserved with short strings first in `row.key`.

```
Composite Key [k1, k2]:       Encoded String row.key:
['aa', 10]           =>      <d64('aa')>!<d64(10)>!
['aa', 12]           =>      <d64('aa')>!<d64(12)>!
['aaa', 10]          =>      <d64('aaa')>!<d64(10)>!
['aab', 10]          =>      <d64('aab')>!<d64(10)>!
['bba', 05]          =>      <d64('bba')>!<d64(05)>!
```

(Because what ever the byte with overhanging bits from `d64('aa')` compares to in `d64('aaa')` it's greater than `!`)

If in the above I want everything where `k1` is exactly `aaa` I'll do the following comparison:

```
        <d64('aa')>!     <=    row.key      <=      <d64('aa')>!~
```

In the example above this will hold for rows `['aa', 10]` and `['aa', 12]`.

But if I want everything that is _prefixed_ `aa` (ie. all rows except `['bba', 05]`) I need `d64.encodeHigh` and would use a query as follows:

```
        <d64('aa')>      <=    row.key      <=      <d64.encodeHigh('aa')>~
```

Obviously, `'aa'` is a prefix of `k1` it is the case that `<d64('aa')> <= row.key`. However, I cannot just use `d64.encode` for the `<=` part. As the overhanging bits in`d64('aa')` may be encode as something greater than 0, in for example `d64('aaa')`. 
The hack seems to be to make the overhanging bits high, using a method like `d64.encodeHigh`, and then append `~` as it'll be greater than anything else prefixed `aa`.
(Ideally `0xff` could be used in place of `~`, but `0xff` isn't printable and can't be used for comparison).

**Note**, if I'm completely crazy or this is totally wrong feel free to let me know.

---

So the argument for adding a method that encodes the overhanging bits as 1. Is not that it is a useful encoding for store data in a database. But that is useful when doing a prefix search of d64 encoded data using the `<=` operator.

If you're interested in adding this, I don't mind writing a PR with a stupid implementation. It looks like some simple bit flipping...

**Comment by dominictarr** [comment]
Oh, this is not so unreasonable, though I think there might be some simpler solutions.

you could just do `d64.encode(Buffer.concat([key, new Buffer([255])]))`
and that would do the same thing, without being coupled or just write a function that incremented a buffer by 1,
and then use less than to mark the high end...*

I feel this would be a better solution, because it would not be coupled to d64, and would also work with another encoding that preserved ordering, such as `hex`.

*(if the last byte is < 255 increment it by one, else set it to zero and repeat on the previous byte, etc)

**Comment by jonasfj** [comment]
Yeah, the alternatives are to decrement (which has a special case for when you can't decremented, in case of prefix for `0xffff`)... Or pad with 0xff (until the input is a multiple of 3) and then add `~` after encoding...

``` js
var toD64High = function(b) {
  // Ensure there are no overflow bits, by adding additional 0xff bytes
  if (b.length % 3 === 1) {
    b = Buffer.concat([b, new Buffer([255, 255])]);
  } else if (b.length % 3 === 2) {
    b = Buffer.concat([b, new Buffer([255])]);
  }
  return d64.encode(b);
};
```

And then the following should work:

```
        <d64('aa')>      <=    row.key      <=      <toD64High('aa')>~
```

---

You might be right that it's overkill to add this as a method. But it might be nice to add some hits to the documentation about how to use `!` as separator and `~` for upper-bound with comparing with `<=`. I love how power this makes a simple key-value store, but it's so easy to get this wrong :)

**Comment by dominictarr** [comment]
I think the this here is you should publish a module for representing
prefix searches as inequalities. I would be happy to link to it from the
readme.
